### PR TITLE
Search

### PR DESCRIPTION
**Pull request by adminq80**
- Search is working Elastic search
- Added checks for startup script to install both Meteor and ElasticSearch if there are not in the system
- Dynamically deleting the ElasticSearch index by running reset script
- Added some files to be ignored in .gitignore file

### CODE REVIEW

**Comment by joegoldbeck** [comment]
Thanks for the great work Abdulrahman! The main thing missing before merge is a system for cycling the streams in elasticsearch (or a similar way to only get the latest results, and delete those results that are old).

Also, I suspect we'll want to do some tunin to get the results really nice. Is there a way to be able to update the settings and mapping on ES automatically when we change them in the code? It would be great to be able to do the tuning locally, and then just push up changes with the rest of our code. Currently, I lowered the min score to 0.1 so we didn't miss results that the Mongo search would have picked up (a search for "dog" gives a good example where ES was otherwise missing some nice puppy cams).

Other than those this looks to be a nice improvement over what we were doing with MongoDB, as we can now rank results by relevance. Looks like once the system is set up there are some really interesting features of ElasticSearch (fuzzy matching, synonyms) that we could start taking advantage of that will make search even better!

**Comment by adminq80** [comment]
Yah I will add the time stamp and add a filter to the query to filter out results above the threshold. 

If the new mapping doesn't match the current mapping weather it guessed it or you provided. So yah we can change the mapping on the fly but we will lose the data, Once the next cycle kicks in we will have new data with the new mapping.

**Comment by joegoldbeck** [comment]
Sounds good!

**Comment by adminq80** [comment]
Hey guys,

Check this one out link
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html#mapping-ttl-field.
So by enabling the _ttl we can set a time interval to invalidate documents
and thus ElasticSearch will delete them automatically.

Abdul

**Pull request merged**
